name: Deploy handbook to Github Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'
            - name: Install dependencies
              run: python3 -m pip install -r ./requirements.txt
            - name: Build and deploy docs
              run: mkdocs gh-deploy

